-- Drizzle baseline migration.
--
-- This baseline represents the existing database schema that was previously
-- managed via Supabase SQL migrations. All tables and functions already exist
-- in the database, so this migration file contains only comments.
--
-- From here forward:
-- - Edit schema in `packages/db/src/schema.ts`
-- - Generate new migrations with `bun run db:generate`
-- - Apply migrations with `bun run db:migrate`
